import { NextPage } from "next";
import Head from "next/head";

const HeadData: NextPage = () => {
    return (
        <Head>
            <title>Yuto Mizuno's HP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/profile.png" />
        </Head>
    )
}

export default HeadData